#!/bin/bash

OWNER_USER="sonaza.com"
OWNER_GROUP="sonaza.com"
REPOSITORY_DIR="/var/www/sonaza.com/sifas-cards.subdomain"

if [ "$(whoami)" != "$OWNER_USER" ]; then
	OWNER="$OWNER_USER:$OWNER_GROUP"
	echo "Current user ($(whoami)) is not the intended owner. Setting file owners to $OWNER."
	chown -R $OWNER $REPOSITORY_DIR
else
	echo "No need to update file owners."
fi
